### ISSUE TITLE
Vehicle call list is empty when Cyberscript is installed.

### ISSUE THREAD

**Issue by Max-Pare** [cyberscript77/release#2]
This doesn't happen 100% of the time, but at somepoint in the playthrough something happens and the vehicle list becomes empty and unusable, there are many users reporting this as well and their solution was to disable Cyberscipt.

**Comment by Billybishop** [comment]
I made a pull request which fixes several CET errors that've been happening; once we get #5 merged in it would be good to test to confirm that this issue has been resolved.
